New version of wmake supporting out-of-tree object and dependency files

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,42 +1,43 @@
 #!/bin/sh
-cd ${0%/*} || exit 1    # run from this directory
+cd ${0%/*} || exit 1    # Run from this directory
 
-# Parse arguments
+# Parse arguments for library compilation without documentation by default
 genDoc=0
 targetType=libso
-. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
+. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
 
 wmakeCheckPwd "$WM_PROJECT_DIR" || {
-    echo "Error: Current directory is not \$WM_PROJECT_DIR"
+    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR"
     echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
 [ -n "$FOAM_EXT_LIBBIN" ] || {
-    echo "Error: FOAM_EXT_LIBBIN not set"
+    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
-# wmake is required for subsequent targets
+# Compile wmake support applications
 (cd wmake/src && make)
 
-# Build ThirdParty sources
+# Compile ThirdParty libraries and applications
 if [ -d "$WM_THIRD_PARTY_DIR" ]
 then
     $WM_THIRD_PARTY_DIR/Allwmake
 else
-    echo "no ThirdParty sources found - skipping"
+    echo "Allwmake: no ThirdParty directory found - skipping"
 fi
 
-# Build OpenFOAM libraries and applications
+# Compile OpenFOAM libraries and applications
 src/Allwmake $targetType $*
 
-# Build OpenFOAM libraries and applications
+# Compile OpenFOAM libraries and applications
 applications/Allwmake $targetType $*
 
 # Optionally build OpenFOAM Doxygen documentation
 [ $genDoc -eq 1 ] && doc/Allwmake
+
 
 # ----------------------------------------------------------------- end-of-file
diff --git a/src/Allwmake b/src/Allwmake
--- a/src/Allwmake
+++ b/src/Allwmake
@@ -1,26 +1,26 @@
 #!/bin/sh
-cd ${0%/*} || exit 1    # run from this directory
+cd ${0%/*} || exit 1    # Run from this directory
 
 # Parse arguments for library compilation
 targetType=libso
-. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
+. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
 
 wmakeCheckPwd "$WM_PROJECT_DIR/src" || {
-    echo "Error: Current directory is not \$WM_PROJECT_DIR/src"
+    echo "Allwmake error: Current directory is not \$WM_PROJECT_DIR/src"
     echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
 [ -n "$FOAM_EXT_LIBBIN" ] || {
-    echo "Error: FOAM_EXT_LIBBIN not set"
+    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
 }
 
 set -x
 
-# update OpenFOAM version strings if required
+# Update OpenFOAM version strings if required
 wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/*/global.? 2>/dev/null
 
 wmakeLnInclude OpenFOAM
@@ -37,8 +37,8 @@ wmake $targetType meshTools
 wmake $targetType edgeMesh
 
 # Decomposition methods needed by dummyThirdParty
+# (dummy metisDecomp, scotchDecomp etc) needed by e.g. meshTools
 parallel/decompose/AllwmakeLnInclude
-# dummyThirdParty (dummy metisDecomp, scotchDecomp etc) needed by e.g. meshTools
 dummyThirdParty/Allwmake $targetType $*
 
 wmake $targetType finiteVolume
@@ -70,20 +70,17 @@ wmake $targetType combustionModels
 regionModels/Allwmake $targetType $*
 lagrangian/Allwmake $targetType $*
 mesh/Allwmake $targetType $*
-
 renumber/Allwmake $targetType $*
-
 fvAgglomerationMethods/Allwmake $targetType $*
 
 wmake $targetType fvMotionSolver
 wmake $targetType engine
-
 wmake $targetType fvOptions
-
 wmake $targetType regionCoupled
 
 postProcessing/Allwmake $targetType $*
 
 wmake $targetType sixDoFRigidBodyMotion
+
 
 # ----------------------------------------------------------------- end-of-file
diff --git a/wmake/wdep b/wmake/wdep
--- a/wmake/wdep
+++ b/wmake/wdep
@@ -3,7 +3,7 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2014 OpenCFD Ltd.
+#   \\  /    A nd           | Copyright (C) 2014 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #-------------------------------------------------------------------------------
 # License
@@ -24,9 +24,14 @@
 #
 # Script
 #     wdep <file>
+#     cat `wdep <file>`
 #
 # Description
 #     Find the dep-file corresponding to <file> and print the path.
+#
+#     Note: wdep MUST be run from the directory containing <file>.
+#     If it proves useful an option could be added to search the local
+#     source-tree for <file> if it is not in the current directory.
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
@@ -38,14 +43,18 @@ usage() {
 
 Usage: $Script <file>
 
-Finds the dep-file corresponding to <file> and print the path.
+Find the dep-file corresponding to <file> in the current directory
+and print the path.
 
 USAGE
     exit 1
 }
 
 
-# Parse options
+#------------------------------------------------------------------------------
+# Parse arguments and options
+#------------------------------------------------------------------------------
+
 while [ "$#" -gt 0 ]
 do
     case "$1" in
@@ -63,13 +72,24 @@ done
 
 
 #------------------------------------------------------------------------------
+# Check <file> is is the current directory
+#------------------------------------------------------------------------------
+
+if [ ! -e $1 ]
+then
+    echo "$Script error: source file $1 is not in the current directory" 1>&2
+    exit 1
+fi
+
+
+#------------------------------------------------------------------------------
 # Check environment variables
 #------------------------------------------------------------------------------
 
-for check in WM_OPTIONS WM_DIR WM_PROJECT_DIR
+for envar in WM_OPTIONS WM_DIR WM_PROJECT_DIR
 do
-    eval test "\$$check" || {
-        echo "$Script error: environment variable \$$check not set" 1>&2
+    eval test "\$$envar" || {
+        echo "$Script error: environment variable \$$envar not set" 1>&2
         exit 1
     }
 done
@@ -79,18 +99,18 @@ done
 # Search up directories tree for the Make sub-directory
 #------------------------------------------------------------------------------
 
-expandpath()
+expandPath()
 {
-    dir=`dirname $1`
+    dir=$(dirname $1)
     cwd=$PWD
     cd $dir
     exPath=$PWD
     cd $cwd
 }
 
-find_target()
+findTarget()
 {
-    expandpath $1
+    expandPath $1
 
     if [ "$exPath" = "$WM_PROJECT_DIR" \
                    -o "$exPath" = "$HOME" \
@@ -102,30 +122,38 @@ find_target()
     elif [ -d "$1/Make" ]; then
         dir=$1
     else
-        find_target "$1/.."
+        findTarget "$1/.."
     fi
 }
 
 fileName=${1##*/}
 
-expandpath $1
+expandPath $1
 
 if echo $exPath | grep "$WM_PROJECT_DIR" > /dev/null
 then
-    objectsDir=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}$(echo $exPath | sed s%$WM_PROJECT_DIR%% )
+    platformPath=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}
+    objectsDir=$platformPath$(echo $exPath | sed s%$WM_PROJECT_DIR%% )
 else
     path=$exPath
     dir=.
     if [ ! -d Make ]
     then
-        find_target .
+        findTarget .
     fi
     appDir=$dir
-    expandpath $appDir/.
+    expandPath $appDir/.
     objectsDir=$appDir/Make/${WM_OPTIONS}$(echo $path | sed s%$exPath%% )
 fi
 
 echo $objectsDir/$fileName.dep
+
+
+#------------------------------------------------------------------------------
+# Cleanup local variables and functions
+#------------------------------------------------------------------------------
+
+unset Script usage expandPath findTarget
 
 
 #------------------------------------------------------------------------------
diff --git a/wmake/wmake b/wmake/wmake
--- a/wmake/wmake
+++ b/wmake/wmake
@@ -26,7 +26,27 @@
 #     wmake
 #
 # Description
-#     General, easy to use make system for multi-platform development.
+#     General, easy to use make system for multi-platform development
+#     with support for local and network parallel compilation.
+#
+#     This updated wmake supports out-of-tree object and dependency files to
+#     avoid the clutter which accumulates in the source-tree with the original
+#     wmake system.  Now when building the OpenFOAM package both the object and
+#     dependency files are now located in a tree with the same structure as the
+#     source tree but in the platforms/$WM_OPTIONS sub-directory of
+#     $WM_PROJECT_DIR.
+#
+#     When building user libraries and applications which are not located in the
+#     OpenFOAM source-tree the object and dependency files are located in a tree
+#     with the same structure as the source tree but in the Make/$WM_OPTIONS
+#     sub-directory.
+#
+#     The disadvantage of the out-of-tree compilation is that the dependency
+#     files are harder to find but are sometimes useful to study which header
+#     files are included.  For those who need access to the dependency files the
+#     new wdep script is provided to locate them.
+#     See the wdep script header or run:
+#         wdep -h
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
@@ -40,34 +60,41 @@ Usage: $Script [OPTION] [dir]
        $Script [OPTION] target [dir [MakeDir]]
 
 options:
-  -s | -silent      invoke make in 'silent' mode (do not echo commands)
-  -a | -all         invoke make in all subdirectories
-  -h | -help        print the usage
+  -s | -silent      Run make in 'silent' mode (do not echo commands)
+  -a | -all         Run wmake in all subdirectories
+  -h | -help        Print the usage
 
 
 A general, easy-to-use make system for multi-platform development
+with support for local and network parallel compilation.
 
 The 'target' is a Makefile target:
-  e.g., Make/linux64GccDPOpt/fvMesh.o
+  e.g., platforms/linux64GccDPOpt/.../fvMesh.o
 
 or a special target:
-  all               all subdirectories, uses any Allwmake files if they exist
-  exe               build statically linked executable
-  lib               build statically linked archive lib (.a)
-  libo              build statically linked lib (.o)
-  libso             build dynamically linked lib (.so)
-  dep               build lnInclude and dependencies only
+  all               wmake all subdirectories, running Allwmake files if present
+  exe               Compile statically linked executable
+  lib               Compile statically linked archive lib (.a)
+  libo              Compile statically linked lib (.o)
+  libso             Compile dynamically linked lib (.so)
+  dep               Compile lnInclude and dependencies only
 
 USAGE
     exit 1
 }
 
 
-# Normally use "make"
+# Default make is the "make" in the path
 make="make"
+
+
+#------------------------------------------------------------------------------
+# Parse arguments and options
+#------------------------------------------------------------------------------
+
+# Default to compiling the local target only
 all=
 
-# Parse options
 while [ "$#" -gt 0 ]
 do
     case "$1" in
@@ -96,17 +123,17 @@ done
 # Check environment variables
 #------------------------------------------------------------------------------
 
-for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
+for envar in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
 do
-    eval test "\$$check" || {
-        echo "$Script error: environment variable \$$check not set" 1>&2
+    eval test "\$$envar" || {
+        echo "$Script error: environment variable \$$envar not set" 1>&2
         exit 1
     }
 done
 
 
-# when compiling anything but a standalone exe:
-# WM_PROJECT and WM_PROJECT_DIR must be set
+# When compiling anything but a standalone exe WM_PROJECT and WM_PROJECT_DIR
+# must be set
 [ "$1" = exe -o \( "$WM_PROJECT" -a "$WM_PROJECT_DIR" \) ] || {
     echo "$Script error:" 1>&2
     echo "    environment variable \$WM_PROJECT or " \
@@ -117,10 +144,10 @@ done
 
 
 #------------------------------------------------------------------------------
-# Select the version of make use
+# Setup parallel compilation
 #------------------------------------------------------------------------------
 
-# set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
+# Set WM_NCOMPPROCS automatically when both WM_HOSTS and WM_SCHEDULER are set
 if [ -z "$WM_NCOMPPROCS" -a -n "$WM_HOSTS" -a -n "$WM_SCHEDULER" ]
 then
     WM_NCOMPPROCS=$(wmakeScheduler -count)
@@ -178,7 +205,7 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Recurse the application directories tree
+# Recurse the source tree to compile "all" targets
 #------------------------------------------------------------------------------
 
 if [ "$all" = "all" ]
@@ -213,24 +240,24 @@ fi
 
 
 #------------------------------------------------------------------------------
-# Search up directories tree for the Make sub-directory and build there
-# Also check the existance of the 'files' file
+# Search up the directory tree for the Make sub-directory,
+# check the existance of the 'files' file and build there if present
 #------------------------------------------------------------------------------
 
 unset dir
 
-expandpath()
+expandPath()
 {
-    dir=`dirname $1`
+    dir=$(dirname $1)
     cwd=$PWD
     cd $dir
     exPath=$PWD
     cd $cwd
 }
 
-find_target()
+findTarget()
 {
-    expandpath $1
+    expandPath $1
 
     if [ "$exPath" = "$WM_PROJECT_DIR" \
                    -o "$exPath" = "$HOME" \
@@ -242,7 +269,7 @@ find_target()
         echo "    Found target directory " $1
         dir=$1
     else
-        find_target "$1/.."
+        findTarget "$1/.."
     fi
 }
 
@@ -251,7 +278,7 @@ then
     echo "$Script: '$MakeDir' directory does not exist in $PWD" 1>&2
     echo "    Searching up directories tree for Make directory"
 
-    find_target .
+    findTarget .
     targetType=
 
     if [ "$dir" ]
@@ -294,15 +321,19 @@ fi
 objectsDir=$MakeDir/$WM_OPTIONS
 if echo $PWD | grep "$WM_PROJECT_DIR"
 then
-    objectsDir=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}$(echo $PWD | sed s%$WM_PROJECT_DIR%% )
+    platformPath=$WM_PROJECT_DIR/platforms/${WM_OPTIONS}
+    objectsDir=$platformPath$(echo $PWD | sed s%$WM_PROJECT_DIR%% )
 fi
 
 (
     unset MAKEFLAGS
     mkdir -p $objectsDir
-    # Pre-build the $WM_OPTIONS/options file which is included
-    # when building the $WM_OPTIONS/files file
-    $make -s -f $WM_DIR/MakefileFiles MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir $objectsDir/options
+
+    # Pre-build the $WM_OPTIONS/options file
+    # which is included when building the $WM_OPTIONS/files file
+    $make -s -f $WM_DIR/MakefileFiles MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir\
+          $objectsDir/options
+
     $make -s -f $WM_DIR/MakefileFiles MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir
 )
 
@@ -328,7 +359,8 @@ case "$targetType" in
         # ... but only if 'LIB' is declared in 'Make/files'
         if grep -e '^ *LIB *=' "$MakeDir/files" >/dev/null 2>&1
         then
-            $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir lnInclude
+            $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir \
+                  OBJECTS_DIR=$objectsDir lnInclude
         fi
         ;;
 esac
@@ -338,7 +370,15 @@ esac
 # Make the dependency files or object files and link
 #------------------------------------------------------------------------------
 
-exec $make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir $targetType
+exec $make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir OBJECTS_DIR=$objectsDir \
+     $targetType
+
+
+#------------------------------------------------------------------------------
+# Cleanup local variables and functions
+#------------------------------------------------------------------------------
+
+unset Script usage expandPath findTarget
 
 
 #------------------------------------------------------------------------------
