wmake/wclean: extend 'all' option to operate within an application directory
Now 'wmake/wclean all' will operate on the current directory and all sub-directories
which contain a 'Make' sub-directory.

This renders Allwmake and Allwclean scripts unnecessary if there is no dependency
between the directory and sub-directories i.e. so specialised libraries

diff --git a/wmake/wmake b/wmake/wmake
--- a/wmake/wmake
+++ b/wmake/wmake
@@ -103,7 +103,8 @@ done
 # WM_PROJECT and WM_PROJECT_DIR must be set
 [ "$1" = exe -o \( "$WM_PROJECT" -a "$WM_PROJECT_DIR" \) ] || {
     echo "$Script error:" 1>&2
-    echo "    environment variable \$WM_PROJECT or \$WM_PROJECT_DIR not set" 1>&2
+    echo "    environment variable \$WM_PROJECT or " \
+         "\$WM_PROJECT_DIR not set" 1>&2
     echo "    while building project library" 1>&2
     exit 1
 }
@@ -180,13 +181,26 @@ then
     then
         ./Allwmake
         exit $?
-    elif [ ! -d $MakeDir ]
-    then
-        # FOAM_APPS=$(find . -maxdepth 1 \( -type d -a ! -name "." -a ! -name Optional -a ! -name Make \)  -printf "%f ")
-        # avoid 'find' with '-printf' ... not entirely portable
-        FOAM_APPS=$(for d in *; do [ -d "$d" -a "$d" != Optional -a "$d" != Make ] && echo "$d"; done | xargs)
-        $make ${WM_CONTINUE_ON_ERROR:+-k} -f $WM_DIR/MakefileApps FOAM_APPS="$FOAM_APPS"
-        exit $?
+    else
+        # Find all the sub-directories containing a 'Make' directory
+        FOAM_APPS=$(\
+                       for d in *; \
+                       do [ -d "$d" -a "$d" != Optional -a "$d" != Make ] \
+                          && echo "$d"; \
+                       done | xargs \
+                 )
+        if [ ! "$FOAM_APPS" = "" ]
+        then
+            # Compile all applications in sub-directories
+            $make ${WM_CONTINUE_ON_ERROR:+-k} \
+                  -f $WM_DIR/MakefileApps FOAM_APPS="$FOAM_APPS"
+        fi
+        # If the current directory contains a 'Make' directory continue
+        # otherwise exit
+        if [ ! -d $MakeDir ]
+        then
+            exit $?
+        fi
     fi
 fi
 
@@ -197,7 +211,6 @@ fi
 #------------------------------------------------------------------------------
 
 unset dir
-MakeDir=Make
 
 expandpath()
 {
@@ -212,7 +225,10 @@ find_target()
 {
     expandpath $1
 
-    if [ "$exPath" = "$WM_PROJECT_DIR" -o "$exPath" = "$HOME" -o "$exPath" = "/" ]
+    if [ "$exPath" = "$WM_PROJECT_DIR" \
+                   -o "$exPath" = "$HOME" \
+                   -o "$exPath" = "/" \
+       ]
     then
         echo "$Script error: could not find Make directory"
     elif [ -d "$1/Make" ]; then
@@ -284,7 +300,8 @@ fi
 OBJECTS_DIR=$MakeDir/$WM_OPTIONS
 
 [ -r $OBJECTS_DIR/objectFiles ] || {
-    echo "$Script error: file '$OBJECTS_DIR/objectFiles' could not be created in $PWD" 1>&2
+    echo "$Script error: file '$OBJECTS_DIR/objectFiles'" \
+         "could not be created in $PWD" 1>&2
     exit 1
 }
 
@@ -297,11 +314,17 @@ touch $OBJECTS_DIR/dontIncludeDeps
 
 case "$targetType" in
 lib | libo | libso | dep )
-    $make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps lnInclude/uptodate
+    $make -s -f $WM_DIR/Makefile \
+          MAKE_DIR=$MakeDir \
+          INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps \
+          lnInclude/uptodate
     ;;
 esac
 
-$make -s -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps $OBJECTS_DIR/dependencies
+$make -s -f $WM_DIR/Makefile \
+      MAKE_DIR=$MakeDir \
+      INCLUDE_DEPS=$OBJECTS_DIR/dontIncludeDeps \
+      $OBJECTS_DIR/dependencies
 
 rc=$?
 [ $rc -eq 0 ] || exit $rc
@@ -313,9 +336,10 @@ rc=$?
 
 if [ "$targetType" != dep ]
 then
-    cmd="$make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir INCLUDE_DEPS=$OBJECTS_DIR/includeDeps $targetType"
-    # echo "cmd=$cmd"
-    exec $cmd
+    cmd="$make -f $WM_DIR/Makefile MAKE_DIR=$MakeDir"
+    incArgs="INCLUDE_DEPS=$OBJECTS_DIR/includeDeps $targetType"
+    exec $cmd $incArgs
 fi
+
 
 #------------------------------------------------------------------------------
